spring:
  application:
    name: ${SPRING_APPLICATION_NAME:eureka-server}

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka-server}